// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteEmployee struct {
	ID int `json:"id"`
}

type Employee struct {
	ID           int    `json:"id"`
	FirstName    string `json:"firstName"`
	LastName     string `json:"lastName"`
	UserName     string `json:"userName"`
	Password     string `json:"password"`
	Email        string `json:"email"`
	Dob          string `json:"dob"`
	DepartmentID int    `json:"departmentId"`
	Position     string `json:"position"`
}

type NewEmployee struct {
	FirstName    string `json:"firstName"`
	LastName     string `json:"lastName"`
	UserName     string `json:"userName"`
	Password     string `json:"password"`
	Email        string `json:"email"`
	Dob          string `json:"dob"`
	DepartmentID int    `json:"departmentId"`
	Position     string `json:"position"`
}

type UpdateEmployee struct {
	ID           int    `json:"id"`
	FirstName    string `json:"firstName"`
	LastName     string `json:"lastName"`
	UserName     string `json:"userName"`
	Password     string `json:"password"`
	Email        string `json:"email"`
	Dob          string `json:"dob"`
	DepartmentID int    `json:"departmentId"`
	Position     string `json:"position"`
}
